name: grouped_list
description: A Flutter ListView where the list items can be grouped into sections.
version: 6.0.0
homepage: https://begnis.dev
repository: https://github.com/Dimibe/grouped_list

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.3 <6.0.0"